### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by freshgum-bubbles** [jellyfin/jellyfin-sdk-typescript#137]
I use this in a project (very nice API btw, thank you!) and just noticed the bundle size is relatively large. A quick look at Bundlephobia[0] tells me that this dependency is nearly a meg compressed. There's also the obvious dependency on Axios[1] which is going to increase the bundle size, but that comes in at 5kB.

EDIT: there's also a tree-shaking problem. Since a class is in use, it looks like Webpack is bundling in everything, even the parts of the API (e.g. SyncPlay) which I do not use.

[0]: https://bundlephobia.com/package/@thornbill/jellyfin-sdk@0.4.1
[1]: https://bundlephobia.com/package/axios@0.26.0

**Comment by freshgum-bubbles** [comment]
There's also some cursory advice here on tree shaking: https://webpack.js.org/guides/tree-shaking/

**Comment by thornbill** [comment]
Thanks for the information! I thought tree shaking was probably not working currently. I will have to do some experimenting with how to best fix this.

**Comment by freshgum-bubbles** [comment]
It's not because, from what I understand, classes are quite finicky to tree-shake. If you had them as individual functions it would be a lot easier to tree-shake from a compiler standpoint :)

I will investigate further and report back. I could probably shave a few bytes off my bundle by making it ES6. It looks like Regenerator Runtime is being included in my bundle for some reason:

```
function(e,t){for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(e[n]=t[n])},r(e,t)},function(e,t){function n(){this.constructor=e}if("function"!=typeof t&&null!==t)throw new TypeError("Class extends value "+String(t)+" is not a constructor or null");r(e,t),e.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}),o=this&&this.__assign||function(){return o=Object.assign||function(e){for(var t,n=1,r=arguments.length;n<r;n++)for(var i in t=arguments[n])Object.prototype.hasOwnProperty.call(t,i)&&(e[i]=t[i]);return e},o.apply(this,arguments)},a=this&&this.__awaiter||function(e,t,n,r){return new(n||(n=Promise))((function(i,o){function a(e){try{u(r.next(e))}catch(e){o(e)}}function s(e){try{u(r.throw(e))}catch(e){o(e)}}function u(e){var t;e.done?i(e.value):(t=e.value,t instanceof n?t:new n((function(e){e(t)}))).then(a,s)}u((r=r.apply(e,t||[])).next())}))},s=this&&this.__generator||function(e,t){function n(n){return function(a){return function(n){if(r)throw new TypeError("Generator is already executing.");
```

**Comment by freshgum-bubbles** [comment]
@thornbill would it help if I emailed you one of those Webpack bundle analysis ,json file thingies I generated from my project? What's your email? I won't send it here as it may contain some PII, ya know. I'm looking at it now and it (thankfully) seems to be mostly the Jellyfin SDK, which means I've mostly done a good job of keeping dependencies down :D

**Comment by thornbill** [comment]
Thanks. I don't think that is necessary. I will revisit this when I get some time. 🙂

**Comment by thornbill** [comment]
I have started work on this in https://github.com/thornbill/jellyfin-sdk-typescript/pull/149.

All the getters for api instances have been replaced with utility functions. In my testing, these needed to be done in individual files for tree-shaking to work correctly.

As far as dropping support for ES5 goes, that's not really ideal currently. jellyfin-web has to support some very old versions of webkits used in TVs, so that limits us somewhat.

I tested these changes using [this very minimal example](https://gist.github.com/thornbill/ae9a04af0b935ca438a9fc8702293b52) and parcel's default configuration for production builds and the results appear to be **very good**.

| version | bundle size |
|:---:|:---:|
| v0.4.1 | 882.27 KB |
| #149 | 132.89 KB |

**Comment by freshgum-bubbles** [comment]
> I have started work on this in #149.

:+1: Subscribed to it :)

> As far as dropping support for ES5 goes, that's not really ideal currently. jellyfin-web has to support some very old versions of webkits used in TVs, so that limits us somewhat.

I could maybe look into compiling this module *myself* under ES6, though I would have to see a noticeable difference as otherwise it's just wasted time... Hmm.

> version 	bundle size
> v0.4.1 	882.27 KB
> #149 	132.89 KB

Man, that's absolutely insane. Good work thornbill :D That's a *lot* better.
