### ISSUE TITLE
how can i use in react native project?

### ISSUE THREAD

**Issue by fenglang0203** [jellyfin/jellyfin-sdk-typescript#198]
how to import sdk in react native project

when I use this:
```
import {Jellyfin} from '@thornbill/jellyfin-sdk'
```
some warning as this:

```
Require cycle: node_modules/@thornbill/jellyfin-sdk/lib/discovery/index.js -> node_modules/@thornbill/jellyfin-sdk/lib/discovery/discovery-service.js -> node_modules/@thornbill/jellyfin-sdk/lib/index.js -> node_modules/@thornbill/jellyfin-sdk/lib/discovery/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: node_modules/@thornbill/jellyfin-sdk/lib/jellyfin.js -> node_modules/@thornbill/jellyfin-sdk/lib/discovery/index.js -> node_modules/@thornbill/jellyfin-sdk/lib/discovery/discovery-service.js -> node_modules/@thornbill/jellyfin-sdk/lib/index.js -> node_modules/@thornbill/jellyfin-sdk/lib/jellyfin.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
```

**Comment by thornbill** [comment]
I attempted to look into this (it was working for me in an Expo app previously), but I encountered a different issue. I’ll try to have an answer/fix for you sometime this week. 🤞

**Comment by fenglang0203** [comment]
Have you made any progress in react Native Project?

**Comment by thornbill** [comment]
The issue that I encountered should be fixed by #202 but that requires some additional work... I have not encountered the issue you are describing. What version of React Native are you using in your project?

**Comment by fenglang0203** [comment]
I use 0.68.1 in my react native project

**Comment by thornbill** [comment]
I did some testing with an app using Expo 45 which uses React Native 0.68.2 and it appears to be working fine there. If they are just warnings does it actually prevent the SDK from working correctly?
