### ISSUE TITLE
Update to node 16 and v3 package lock format

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-sdk-typescript#225]
Our workflows are still using node 14 and 16 is the current LTS. We should update the workflows to use node 16 and update the `package-lock.json` to the ~~v2~~ v3 format used by newer versions of npm.

**Comment by faiz-ali-khan-developer** [comment]
Hey can you assign me this issue

**Comment by ferferga** [comment]
Why not v3 directly?

**Comment by thornbill** [comment]
@ferferga does renovate support v3? I honestly did not know they had already incremented it again.

**Comment by ferferga** [comment]
@thornbill Yes, we use it in Vue since day 1.

Much faster at installing packages and you can enforce it using .npmrc
