### ISSUE TITLE
Deprecate package under the @thornbill namespace

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-sdk-typescript#269]
Once this is published under the `@jellyfin` namespace on npm, the package under my personal `@thornbill` namespace should be deprecated.

https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

**Comment by ferferga** [comment]
If it doesn't have enough downloads, I think it can also be unpublished directly

https://docs.npmjs.com/policies/unpublish

**Comment by nielsvanvelzen** [comment]
I think we should not unpublish, the package is used in 10.8.z released so building those will break when the package is unpublised.

**Comment by thornbill** [comment]
The package has been marked as deprecated with a message to use the new one. It is not unpublished due to the reason above.
