### ISSUE TITLE
"Usage" in Readme.md not working

### ISSUE THREAD

**Issue by smoebody** [jellyfin/jellyfin-sdk-typescript#292]
Hi,

I wanted to test the api, but the usage example is incomplete. The import statements are missing entirely and i cannot find out what to import in order to get the `getSystemApi()`, `getUserApi()` or `getLibraryApi()` functions.

Can you please clarify.

cheers

**Comment by thornbill** [comment]
Here is a full example with the import statements. https://gist.github.com/thornbill/ae9a04af0b935ca438a9fc8702293b52
