### ISSUE TITLE
Axios not requesting serverip

### ISSUE THREAD

**Issue by prayag17** [jellyfin/jellyfin-sdk-typescript#340]
When I try to execute the following code:

```js
import { useContext } from "react";
import { Cookies, useCookies } from "react-cookie";
import { jellyfin } from "../../jellyfin";
// import getSystemApi from "@jellyfin/sdk";
import { getSystemApi } from "@jellyfin/sdk/lib/utils/api/system-api";

export const UserLogin = () => {
	const [serversListCookies] = useCookies(["servers"]);
	const cookies = new Cookies();
	const currentServer = cookies.get("currentServer");
	const api = jellyfin.createApi(cookies.get(currentServer));

	const tp = async () => {
		const info = await getSystemApi(api).getPublicSystemInfo();
		console.log(info.data);
	};

	tp();

	return (
		<>
			<h1 color="white">WIP-user login</h1>
		</>
	);
};
```
I get thee following  error:
![image](https://user-images.githubusercontent.com/55829513/204138091-b408c284-d9dd-41f9-a07b-313837b97c4e.png)

for some reason it requests localhost instead of the actual server

**Comment by thornbill** [comment]
Your code that reads the server info from cookies looks very wrong. I'm surprised you aren't getting an error when you create the api instance. 😅

**Comment by prayag17** [comment]
Oh yeah thanks, I forgot to add `.ip` at the end of `cookies.get(currentServer)` it works now.
Thanks
