### ISSUE TITLE
Publish to npm with provenance

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-sdk-typescript#471]
https://github.blog/changelog/2023-04-19-npm-provenance-public-beta/

**Comment by j4ckofalltrades** [comment]
I've started working on this in PR #571.

**Comment by thornbill** [comment]
Starting with the v0.9.0 release, the npm package is published with provenance: https://www.npmjs.com/package/@jellyfin/sdk/v/0.9.0
