### ISSUE TITLE
Missing endpoint /user/me

### ISSUE THREAD

**Issue by bu3alwa** [jellyfin/jellyfin-sdk-typescript#551]
Hey,

The SDK doesn't seem to expose /user/me so I am unable to call this validate the key for a logged in user. It seems like it didn't get generated in the generated-clients.

Is there are reason for it being removed or just the generation not working correctly?

**Comment by thornbill** [comment]
It should be here: https://typescript-sdk.jellyfin.org/classes/generated_client.UserApi.html#getCurrentUser

**Comment by bu3alwa** [comment]
Oh I was looking for me so I guess I missed getCurrentUser. Thanks.
