### ISSUE TITLE
Add startLimit option to PersonsApi.getPersons()

### ISSUE THREAD

**Issue by prayag17** [jellyfin/jellyfin-sdk-typescript#562]
currently when fetching all Persons for a particular Library the `getPersons()` Fn doesn't have a `startIndex` to allow for pagination. It would be nice to add the startIndex property from `ItemsApi.getItems` Fn.

**Comment by jwetzell** [comment]
The jellyfin [core](https://github.com/jellyfin/jellyfin) would need to add the `startIndex` query parameter for the `/Persons` [endpoint](https://api.jellyfin.org/#tag/Persons) for this library to be able to add it.

**Comment by thornbill** [comment]
Yeah you should open an issue on the server repo to request this.
