### ISSUE TITLE
Remove ItemSortBy enum from models/api

### ISSUE THREAD

**Issue by 3flex** [jellyfin/jellyfin-sdk-typescript#840]
[This](https://github.com/jellyfin/jellyfin-sdk-typescript/blob/master/src/models/api/item-sort-by.ts) should not be needed since there's an [`ItemSortBy` in the generated client](https://github.com/jellyfin/jellyfin-sdk-typescript/blob/master/src/generated-client/models/item-sort-by.ts) since sources were regenerated for Jellyfin 10.9.0.

I can make the PR easily, just looking for a 👍 to make sure this is the right thing to do.

**Comment by thornbill** [comment]
👍 good find! A pr would be most welcome!
